name: "Khadas VIM3 Fan Controller"
description: "Control the fan of the Khadas VIM3"
version: "1.0.3"
slug: "khadas-vim3-fan"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
log_level: info
startup: services
privileged:
  - SYS_ADMIN
devices:
  - /dev/i2c-0
ingress: true
options:
  threshold_1: 40000
  threshold_2: 60000
  threshold_3: 80000
  tolerance: 2500
  interval: 30
schema:
  threshold_1: int
  threshold_2: int
  threshold_3: int
  tolerance: int
  interval: int
