name: "Khadas VIM3 Fan Controller"
description: "Control the fan of the Khadas VIM3"
version: "1.0.0"
slug: "khadas-vim3-fan"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
log_level: info
startup: services
privileged:
  - SYS_ADMIN
devices:
  - /dev/i2c-0
ingress: true
